use std::{
    env::var,
    fs::{File, create_dir_all},
    io::Write,
    path::Path,
    process::Command,
    thread::available_parallelism,
    time::{SystemTime, UNIX_EPOCH},
};

fn run_cmd_trimmed(cmd: &mut Command) -> Option<String> {
    match cmd.output() {
        Ok(out) if out.status.success() => {
            let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if s.is_empty() { None } else { Some(s) }
        },
        _ => None,
    }
}

fn main() {
    let git_hash = run_cmd_trimmed(
        Command::new("git").arg("rev-parse").arg("--short").arg("HEAD"),
    )
    .unwrap_or_else(|| "unknown".into());
    let git_commit_date = run_cmd_trimmed(
        Command::new("git")
            .arg("show")
            .arg("-s")
            .arg("--format=%cI")
            .arg("HEAD"),
    )
    .unwrap_or_else(|| "unknown".into());

    let rustc_version = run_cmd_trimmed(Command::new("rustc").arg("--version"))
        .unwrap_or_else(|| "unknown".into());

    let profile = var("PROFILE").unwrap_or_else(|_| "unknown".into());
    let target = var("TARGET").unwrap_or_else(|_| "unknown".into());

    let build_time_secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    let num_cpus = available_parallelism().map(|n| n.get()).unwrap_or(1);

    let out_dir = Path::new("src");
    let out_file = out_dir.join("build_constants.rs");

    let contents = format!(
        r#"/// Generated by build script. Do not edit.
        pub const BUILD_GIT_HASH: &str = "{git_hash}";
        pub const BUILD_GIT_COMMIT_DATE: &str = "{git_commit_date}";
        pub const BUILD_RUSTC_VERSION: &str = "{rustc_version}";
        pub const BUILD_PROFILE: &str = "{profile}";
        pub const BUILD_TARGET: &str = "{target}";
        pub const BUILD_TIME_SECS: u64 = {build_time_secs};
        pub const BUILD_NUM_CPUS: usize = {num_cpus};
        "#,
        git_hash = git_hash,
        git_commit_date = git_commit_date,
        rustc_version = rustc_version,
        profile = profile,
        target = target,
        build_time_secs = build_time_secs,
        num_cpus = num_cpus
    );

    if let Err(e) = create_dir_all(out_dir) {
        println!("cargo:warning=failed to create src directory: {}", e);
    }

    match File::create(&out_file) {
        Ok(mut f) => {
            if let Err(e) = f.write_all(contents.as_bytes()) {
                println!(
                    "cargo:warning=failed to write {}: {}",
                    out_file.display(),
                    e
                );
            }
        },
        Err(e) => {
            println!(
                "cargo:warning=failed to create {}: {}",
                out_file.display(),
                e
            );
        },
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/refs/heads");
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=TARGET");
    println!(
        "cargo:warning=build constants: git={} profile={} target={}",
        git_hash, profile, target
    );
}
